apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: knvvtam1u-nodejs 
  janus-idp.io/tekton: knvvtam1u-nodejs
  backstage.io/kubernetes-id: knvvtam1u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: knvvtam1u-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  